### PR TITLE
fix memory qos blog

### PR DESCRIPTION
**Pull request by saintube**
Fix Memory QoS's instructions in the blog *What's New in Koordinator v0.3.0?*.

Signed-off-by: saintube <saintube@foxmail.com>

### CODE REVIEW

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Review by eahydra — APPROVED** [review]
/lgtm
/approve

**Review by jasonliu747 — CHANGES_REQUESTED** [review]
image
空格

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Pull request merged**
